
import numpy
print("2*2 ones matrix:", numpy.ones((2, 2)), sep='\n')
arr = numpy.array([1, 3, 11, 4, 3, 8, 1, 4])
print("arr:", arr)
print("make arr unique:", numpy.unique(arr))
print("arrays are immutable :", arr)   # arr is immutable
arr1 = numpy.arange(0, 10, dtype='i', step=2)
arr2 = numpy.arange(1, 10, dtype='i', step=2)
print("arr1:", arr1)
print("arr2:", arr2)
print("arr1 + arr2:", arr1+arr2)
print("arr1 - arr2:", arr1-arr2)
print("arr1 * arr2:", arr1*arr2)
print("arr1 / arr2:", arr1/arr2)
print("[ arr1 arr2]:", numpy.append(arr1, arr2))
print("[ arr2 arr1]:", numpy.insert(arr1, 0, arr2))
print("delete element with index 2 in arr1:", numpy.delete(arr1, 2))
print("arr1 min element:", numpy.amin(arr1))
print("arr2 min element:", numpy.amin(arr2))
print("arr1 max element:", numpy.amax(arr1))
print("arr2 max element:", numpy.amax(arr2))
print("arr1 average is:", numpy.average(arr1))
print("arr2 average is:", numpy.average(arr2))
print("arr1 median is:", numpy.median(arr1))
print("arr2 median is:", numpy.median(arr2))
print("arr1 variance: ", numpy.var(arr1))
print("arr2 variance: ", numpy.var(arr2))
arr3 = arr2
print("arr3 is arr2:", arr3 is arr2)
arr3 = arr2.copy()
print("arr3 is arr2:", arr3 is arr2)
arr1 = arr1[::-1]
print("reversed arr1", arr1)
arr1 = numpy.sort(arr1)
print("sorted reversed arr1", arr1)
print("arr2 > 5 elements", arr2 > 5)
print("arr1 elements sqrt", numpy.sqrt(arr1))
print("arr1 elements square", numpy.square(arr1))
print("arr2 elements cube", numpy.power(arr2, 3))
